repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.18
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.9
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: builtin
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-json
      - id: detect-private-key
