apiVersion: v3.1.0
kind: DataContract
id: multi_layout
version: 0.0.1
status: draft
name: Multi-Layout Test
schema:
  - name: "9001"
    businessName: ""
    description: ""
    type: object
    properties:
      - name: record_type
        logicalType: integer
        description: ""
        required: true
        quality:
          - type: library
            metric: nullValues
            mustBe: 0
            name: Not Null
      - name: account_id
        logicalType: string
        description: ""
        required: true
        quality:
          - type: library
            name: Not Null
            metric: nullValues
            mustBe: 0
  - name: Header
    businessName: ""
    description: ""
    type: object
    properties:
      - name: record_type
        logicalType: string
        description: ""
        required: true
      - name: file_name
        logicalType: string
        description: ""
      - name: creation_date
        logicalType: timestamp
        description: ""
  - name: Trailer
    businessName: ""
    description: ""
    type: object
    properties:
      - name: record_type
        logicalType: string
        description: ""
      - name: 9001_record_count
        logicalType: string
        description: ""
      - name: 9002_record_count
        logicalType: string
        description: ""
      - name: 9004_record_count
        logicalType: string
        description: ""
