[runtime]
log_level="INFO"  # the system log level of dlt
dlthub_telemetry = false

[destination.filesystem]
kwargs = '{"auto_mkdir": true}'

[sources.data_writer]
file_format = "parquet"

[normalize.data_writer]
file_max_items=1000000
file_max_bytes=1000000
